// Objective-C API for talking to palindrome/core Go package.
//   gobind -lang=objc palindrome/core
//
// File is generated by gobind. Do not edit.

#ifndef __GoPalindromeCheck_H__
#define __GoPalindromeCheck_H__

#include <Foundation/Foundation.h>

FOUNDATION_EXPORT BOOL GoPalindromeCheckIsPalindrome(NSString* candidate);

#endif
